version: '3'

services:
  backend:
    image: mysql
    volumes:
      - ./backend/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 5000:80

  frontend:
    #image: php:apache
    build: ./frontend
    volumes:
       - ./frontend:/var/www/html
    ports:
       - 80:80
    depends_on:
       - backend
