version: '3'

services:
  backend:
    image: mysql
    volumes:
      - ./backend/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 5000:80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #volumes:
       #- ./frontend:/usr/src/app
       #- ./frontend:/var/www/html
    ports:
       - 80:80
    depends_on:
       - backend
